title: Security Forge
description: Cybersecurity | Pentesting | Vulnerability Research 
author: Artur
email: agakhanyantsartur@gmail.com

# Theme
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme


show_downloads: false

# Socials
github_username: r3so1ve
linkedin_username: artur-agakhanyants

# URL 
url: "https://r3so1ve.github.io"
baseurl: ""

# Build settings
markdown: kramdown

theme: null
permalink: /:categories/:title/
timezone: Asia/Tashkent

# Navbar links
navbar:
  - title: Blog
    url: /blog/
  - title: About
    url: /about/